# Configuración de la Base de Datos
# Este archivo debe estar en la misma ubicación que el archivo .jar

# Ruta de la base de datos SQLite
# Puede ser una ruta absoluta o relativa al directorio del JAR
# Ejemplos:
#   Ruta absoluta: database_path=C:\MiCarpeta\mi_base_de_datos.db
#   Ruta relativa: database_path=prueba.db (se creará en el mismo directorio del JAR)
#   Ruta relativa con subcarpeta: database_path=data\prueba.db

database_path=C:\Users\senis\OneDrive\Escritorio\algo.db


